language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:v-launchpad-jochen-sprickerhof-de/pcl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:kalakris/cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y cmake libpcl-all libglew-dev libglm-dev libXxf86vm-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/glfw/glfw.git; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd glfw; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git checkout 3.0.3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake -DBUILD_SHARED_LIBS=ON; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .; fi

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux