language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install libpcl-all glew glm glfw; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .; fi
  - make

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux